import mongoose from "mongoose";
// import { validate } from "node-cron";
import validator from "validator";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";

const schema = new mongoose.Schema({
  // Name type, required
  name: {
    type: String,
    required: [true, "Please Enter your name "],
  },
  //   Email type, required, unique, validate
  email: {
    type: String,
    required: [true, "Please Enter your email"],
    unique: true,
    validate: validator.isEmail,
  },
  //   Password type, required, minLength, select
  password: {
    type: String,
    required: [true, "Please enter your password"],
    minLength: [6, "Password must be atleast of 6 character"],
    select: false,
  },
  //   Role type, enum, default
  role: {
    type: String,
    enum: ["admin", "user"],
    default: "user",
  },
  //   Subscription id, status
  subscription: {
    id: String,
    status: String,
  },
  //   Avatar public_id, url
  avatar: {
    public_id: {
      type: String,
      required: true,
    },
    url: {
      type: String,
      required: true,
    },
  },
  //   Playlist [ courseId,poster ]
  playlist: [
    {
      course: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Course",
      },
      poster: String,
    },
  ],
  //   CreatedAt type, default
  createdAt: {
    type: Date,
    default: Date.now(),
  },
  //   ResetPasswordToken type
  ResetPasswordToken: String,
  //   ResetPasswordExpire type
  ResetPasswordExpire: String,
});

//Encrypt Password & Used PreSave from bcrypt library
schema.pre("save", async function (next) {
  if (!this.isModified("password")) return next();
  this.password = await bcrypt.hash(this.password, 10); //10 round will use to store the password
  next();
});
schema.methods.getJWTToken = function () {
  return jwt.sign({ _id: this._id }, process.env.JWT_SECRET, {
    expiresIn: "15d",
  }); //Every individual user has there id generated by MONGODB that's why _id and this._id is used for getting _id from Mongodb of user
};

schema.methods.comparePassword = async function (password) {
  console.log(this.password);
  return await bcrypt.compare(password, this.password);
};

const User = mongoose.model("User", schema);

export default User;
